### ISSUE TITLE
error while mouseout

### ISSUE THREAD

**Issue by zhbzhbzhbz** [NikitaKA/jquery.dragOptions#2]
After I "mousedown" on a option, then moved my mouse out of the 《select》 (or below the last 《option》) , then "mouseup", 
the mouseup function won't be called.
Maybe it's a difficuult problem. Thanks~

**Comment by zhbzhbzhbz** [comment]
I made a tricky solution.
1)Above "a.fn.extend"
```
var topLine = 0;
var buttomLine = 10000;
```
2)At the top of "mousemove", 
```
var yPosition = event.originalEvent.y || event.originalEvent.layerY || 0;
if(yPosition >= buttomLine || yPosition<=topLine){
    a(this).trigger("mouseup");
    return false;
}
```
3)At the bottom of "mousedown",
topLine = e.find('option:first').offset().top + e.find('option:first').height()/4; 
var lastOptionCenter = e.find('option:last').offset().top + e.find('option:last').height()/4*3
var selectButtom = e.offset().top+e.height()-e.find('option:last').height()/4;
buttomLine = Math.min(lastOptionCenter,selectButtom);

**Comment by NikitaKA** [comment]
I think the better way is to work with `mouseleave` event attached to `select` element. I'll see what can be done with this.

**Comment by zhbzhbzhbz** [comment]
Yeah, but if I move the mouse below the last `option` and above the buttom of the `select` element, the `mouseleave` event of `select` won't be triggered and the existing `mouseup` event won't be triggered correctly when I release the mouse at that position either ...

**Comment by NikitaKA** [comment]
Oh, didn't figured that out. Now I see, sorry. This is interesting... let me think, maybe I will find more cute solution.

**Comment by NikitaKA** [comment]
Here what I got: [http://output.jsbin.com/peguxesezi](http://output.jsbin.com/peguxesezi), can you test that? Also fixed bug when mouse leaving `select`, now `mouseup` is triggered too. Firefox and Chrome seems to be okay with that.

**Comment by zhbzhbzhbz** [comment]
Perfect !~
