### ISSUE TITLE
Jquery change/onchange event is not working

### ISSUE THREAD

**Issue by prashant314** [NikitaKA/jquery.dragOptions#5]
If dragoptions is used with a select dropdown, then the change/onchange event is not firing as expected. 
If dragoptions is not used then the change event is received as expected.

I want an event whenever an item is selected to perform some other operations. So, is there any solution for it or am I doing something wrong.  Thanks in advance.

**Comment by NikitaKA** [comment]
Check `issue-5` branch, maybe it will help you. Look at example code, there is new `onSelect` callback.

**Comment by prashant314** [comment]
Thanks @NikitaKA  for the solution. It did work. I thought of doing it the same way.
You can put this in the master branch too, maybe someone will find it useful.
Great work!!
